API 6150 get duz support
department-of-veterans-affairs/lighthouse-charon pull request #73
Opened 2021-04-13 17:05 UTC by bschofield-va

- wip - jaas
- wip - jaas
- wip - standard user session instead of jaas
- User demographics ITs Includes system definition updates - rpcPrincipla is renamed to avCodeRpcPrincipal to better reflect the usage - New value "vistaSite" that is separate targets.   - Defaults to 673 (tampa) in all environments and does not require DU updates   - Will use vista.site system property or VISTA_SITE environment variable if available

2021-04-14 14:46 UTC, eclendenning-va commented on charon-tests/request.json
> +    "verifyCode":"321LIGHTHOUSE*"
secret?

2021-04-14 14:46 UTC, eclendenning-va commented on charon-tests/src/test/java/gov/va/api/lighthouse/charon/tests/UserDemographicsIT.java
> +  void userDemographicsRequiresAccessVerifyCodes() {
cruft?

2021-04-14 16:59 UTC, bschofield-va commented on charon-tests/request.json
> +    "verifyCode":"321LIGHTHOUSE*"
I didn't meant commit that file... will delete

2021-04-14 16:59 UTC, bschofield-va commented on charon-tests/src/test/java/gov/va/api/lighthouse/charon/tests/UserDemographicsIT.java
> +  void userDemographicsRequiresAccessVerifyCodes() {
yes... will delete

2021-04-14 17:33 UTC, eclendenning-va approved these changes

2021-04-14 18:00 UTC, jhulbert-va requested changes

2021-04-14 18:00 UTC, jhulbert-va commented on charon-tests/src/test/java/gov/va/api/lighthouse/charon/tests/UserDemographicsIT.java
> +  @ValueSource(strings = {"/", "/charon/"})
These will fail in a real environment. `/` doesn't map from the load balancer.

2021-04-16 12:23 UTC, jhulbert-va approved these changes

2021-04-16 12:23 UTC, jhulbert-va commented on charon-tests/src/main/java/gov/va/api/lighthouse/charon/tests/SystemDefinitions.java
> +        .vistaSite(systemPropertyOrEnvVar("vista.site", "673"))
Do we want to add this configuration to the entrypoint so we can override it in different environments?

2021-04-16 12:35 UTC, ilaflamme-va approved these changes

2021-04-16 13:14 UTC, bschofield-va commented on charon-tests/src/main/java/gov/va/api/lighthouse/charon/tests/SystemDefinitions.java
> +        .vistaSite(systemPropertyOrEnvVar("vista.site", "673"))
when needed ...

2021-04-16 13:15 UTC, merged