API-8003-parser
department-of-veterans-affairs/lighthouse-charon pull request #93
Opened 2021-06-14 19:53 UTC by jhulbert-va

# [API-8003](https://vajira.max.gov/browse/API-8003)

2021-06-14 20:11 UTC, eclendenning-va commented on charon-models/src/main/java/gov/va/api/lighthouse/charon/models/EntryParser.java
> +public interface EntryParser<E> {
Did we want EntryParser to also Define parseNewLineDelimited?

2021-06-14 21:18 UTC, eclendenning-va approved these changes

2021-06-14 21:42 UTC, bschofield-va commented on charon-models/src/main/java/gov/va/api/lighthouse/charon/models/iblhsamcmsgetins/GetInsEntryParser.java
> +    String[] caretSeparated = entry.split("\\^", -1);
This is _acceptable_ but not _optimal_. Split on regex will (a) recompile the expression repeatedly, (b) be slow. A tokernizer approach is more code, but more performant.

2021-06-14 22:22 UTC, bschofield-va requested changes
hol up ... those exceptions don't seem right. lemme investigate

2021-06-14 22:37 UTC, bschofield-va commented on charon-models/src/test/java/gov/va/api/lighthouse/charon/models/iblhsamcmsgetins/GetInsEntryParserTest.java
> +        arguments(NullPointerException.class, "^2^3^4^5"),
yeah, this doesn't seem right, these should all be through Illegal Argument.

2021-06-14 22:46 UTC, bschofield-va commented on charon-models/src/main/java/gov/va/api/lighthouse/charon/models/iblhsamcmsgetins/GetInsEntryParser.java
> +    String[] caretSeparated = entry.split("\\^", -1);
I stand corrected. I could not implement a parser that is faster. Turns out `string.split(...)` has some interesting short circuit logic for cases just like this that make it ridiculously fast.

2021-06-14 22:47 UTC, bschofield-va commented on charon-models/src/main/java/gov/va/api/lighthouse/charon/models/iblhsamcmsgetins/GetInsEntryParser.java
> +    return GetInsEntry.builder()
```
    try {
      return GetInsEntry.builder()
          .fileNumber(csv.get(0))
          .ien(csv.get(1))
          .fieldNumber(csv.get(2))
          .externalValueRepresentation(csv.get(3))
          .internalValueRepresentation(csv.get(4))
          .build();
    } catch (NullPointerException e) {
      throw new IllegalArgumentException("Illegal field values: " + e.getMessage(), e);
    }
    ```

2021-06-15 12:48 UTC, jhulbert-va commented on charon-models/src/test/java/gov/va/api/lighthouse/charon/models/iblhsamcmsgetins/GetInsEntryParserTest.java
> +        arguments(NullPointerException.class, "^2^3^4^5"),
The NPE's end up getting thrown by Lomboks `@NonNull`

2021-06-15 13:37 UTC, eclendenning-va approved these changes

2021-06-15 17:10 UTC, bschofield-va approved these changes

2021-06-15 17:11 UTC, merged